namespace SimpleStart.Core;

public static class Constants
{
    public static readonly string[] States = new string[] {
            "Alabama",
            "Alaska",
            "Arizona",
            "Arkansas",
            "California",
            "Colorado",
            "Connecticut",
            "Delaware",
            "District Of Columbia",
            "Florida",
            "Georgia",
            "Hawaii",
            "Idaho",
            "Illinois",
            "Indiana",
            "Iowa",
            "Kansas",
            "Kentucky",
            "Louisiana",
            "Maine",
            "Maryland",
            "Massachusetts",
            "Michigan",
            "Minnesota",
            "Mississippi",
            "Missouri",
            "Montana",
            "Nebraska",
            "Nevada",
            "New Hampshire",
            "New Jersey",
            "New Mexico",
            "New York",
            "North Carolina",
            "North Dakota",
            "Ohio",
            "Oklahoma",
            "Oregon",
            "Pennsylvania",
            "Rhode Island",
            "South Carolina",
            "South Dakota",
            "Tennessee",
            "Texas",
            "Utah",
            "Vermont",
            "Virginia",
            "Washington",
            "West Virginia",
            "Wisconsin",
            "Wyoming",
        };
    public static readonly string[] StatesAbbreviated = new string[] {
            "AL",
            "AK",
            "AZ",
            "AR",
            "CA",
            "CO",
            "CT",
            "DE",
            "DC",
            "FL",
            "GA",
            "HI",
            "ID",
            "IL",
            "IN",
            "IA",
            "KS",
            "KY",
            "LA",
            "ME",
            "MD",
            "MA",
            "MI",
            "MN",
            "MS",
            "MO",
            "MT",
            "NE",
            "NV",
            "NH",
            "NJ",
            "NM",
            "NY",
            "NC",
            "ND",
            "OH",
            "OK",
            "OR",
            "PA",
            "RI",
            "SC",
            "SD",
            "TN",
            "TX",
            "UT",
            "VT",
            "VA",
            "WA",
            "WV",
            "WI",
            "WY",
        };
    public static string GetAbbreviationFromState(this string state)
        {
            return state.ToUpper() switch
            {
                "ALABAMA" => "AL",
                "ALASKA" => "AK",
                "AMERICAN SAMOA" => "AS",
                "ARIZONA" => "AZ",
                "ARKANSAS" => "AR",
                "CALIFORNIA" => "CA",
                "COLORADO" => "CO",
                "CONNECTICUT" => "CT",
                "DELAWARE" => "DE",
                "DISTRICT OF COLUMBIA" => "DC",
                "FEDERATED STATES OF MICRONESIA" => "FM",
                "FLORIDA" => "FL",
                "GEORGIA" => "GA",
                "GUAM" => "GU",
                "HAWAII" => "HI",
                "IDAHO" => "ID",
                "ILLINOIS" => "IL",
                "INDIANA" => "IN",
                "IOWA" => "IA",
                "KANSAS" => "KS",
                "KENTUCKY" => "KY",
                "LOUISIANA" => "LA",
                "MAINE" => "ME",
                "MARSHALL ISLANDS" => "MH",
                "MARYLAND" => "MD",
                "MASSACHUSETTS" => "MA",
                "MICHIGAN" => "MI",
                "MINNESOTA" => "MN",
                "MISSISSIPPI" => "MS",
                "MISSOURI" => "MO",
                "MONTANA" => "MT",
                "NEBRASKA" => "NE",
                "NEVADA" => "NV",
                "NEW HAMPSHIRE" => "NH",
                "NEW JERSEY" => "NJ",
                "NEW MEXICO" => "NM",
                "NEW YORK" => "NY",
                "NORTH CAROLINA" => "NC",
                "NORTH DAKOTA" => "ND",
                "NORTHERN MARIANA ISLANDS" => "MP",
                "OHIO" => "OH",
                "OKLAHOMA" => "OK",
                "OREGON" => "OR",
                "PALAU" => "PW",
                "PENNSYLVANIA" => "PA",
                "PUERTO RICO" => "PR",
                "RHODE ISLAND" => "RI",
                "SOUTH CAROLINA" => "SC",
                "SOUTH DAKOTA" => "SD",
                "TENNESSEE" => "TN",
                "TEXAS" => "TX",
                "UTAH" => "UT",
                "VERMONT" => "VT",
                "VIRGIN ISLANDS" => "VI",
                "VIRGINIA" => "VA",
                "WASHINGTON" => "WA",
                "WEST VIRGINIA" => "WV",
                "WISCONSIN" => "WI",
                "WYOMING" => "WY",
                _ => state
            };
        }
    public static string GetStateFromAbbreviation(this string stateCode)
        {
            return stateCode.ToUpper() switch
            {
                "AL" => "Alabama",
                "AK" => "Alaska",
                "AS" => "American Samoa",
                "AZ" => "Arizona",
                "AR" => "Arkansas",
                "CA" => "California",
                "CO" => "Colorado",
                "CT" => "Connecticut",
                "DE" => "Delaware",
                "DC" => "District Of Columbia",
                "FM" => "Federated States Of Micronesia",
                "FL" => "Florida",
                "GA" => "Georgia",
                "GU" => "Guam",
                "HI" => "Hawaii",
                "ID" => "Idaho",
                "IL" => "Illinois",
                "IN" => "Indiana",
                "IA" => "Iowa",
                "KS" => "Kansas",
                "KY" => "Kentucky",
                "LA" => "Louisiana",
                "ME" => "Maine",
                "MH" => "Marshall Islands",
                "MD" => "Maryland",
                "MA" => "Massachusetts",
                "MI" => "Michigan",
                "MN" => "Minnesota",
                "MS" => "Mississippi",
                "MO" => "Missouri",
                "MT" => "Montana",
                "NE" => "Nebraska",
                "NV" => "Nevada",
                "NH" => "New Hampshire",
                "NJ" => "New Jersey",
                "NM" => "New Mexico",
                "NY" => "New York",
                "NC" => "North Carolina",
                "ND" => "North Dakota",
                "MP" => "Northern Mariana Islands",
                "OH" => "Ohio",
                "OK" => "Oklahoma",
                "OR" => "Oregon",
                "PW" => "Palau",
                "PA" => "Pennsylvania",
                "PR" => "Puerto Rico",
                "RI" => "Rhode Island",
                "SC" => "South Carolina",
                "SD" => "South Dakota",
                "TN" => "Tennessee",
                "TX" => "Texas",
                "UT" => "Utah",
                "VT" => "Vermont",
                "VI" => "Virgin Islands",
                "VA" => "Virginia",
                "WA" => "Washington",
                "WV" => "West Virginia",
                "WI" => "Wisconsin",
                "WY" => "Wyoming",
                _ => stateCode
            };
        }
    
}