name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*' # Trigger on version tags v1.0.0, v2.1.3, etc.
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Using a newer SDK to build .NET Standard 2.0 libraries
      
      - name: Display .NET information
        run: dotnet --info
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build --configuration Release --no-restore
        
      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Pack
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          if [ -z "$VERSION" ]; then
            # If running manually without a tag, use the version from csproj
            dotnet pack --configuration Release --no-build --output ./nupkgs
          else
            # Use the tag version
            dotnet pack --configuration Release --no-build --output ./nupkgs /p:Version=$VERSION
          fi
          
      - name: List created packages
        run: ls -la ./nupkgs

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
